# Development database
services:
  dev-db:
    image: postgres:13 # Specify the image
    ports:
      - 5434:5432 # Corrected indentation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp # Service connected to the network

# test database setup
  test-db:
    image: postgres:13 # Specify the image
    ports:
      - 5435:5432 # Corrected indentation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp # Service connected to the network

networks:
  freecodecamp: # Defined the network
    driver: bridge
